# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyO0
baud: 57600
timeout: 0.1

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_link

# === Robot drivetrain parameters
wheel_diameter: 0.0625
wheel_track: 0.2794
encoder_resolution: 8356 # http://www.robotshop.com/en/pololu-12v-29-1-gear-motor-encoder.html
gear_reduction: 29 #29:1
motors_reversed: True

# === PID parameters
Kp: 10
Kd: 12
Ki: 0
Ko: 50
accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  ir_front_left:        {pin: A6, type: GP2D12, rate: 10},
  ir_front_center:      {pin: A7, type: GP2D12, rate: 10},
  ir_front_right:       {pin: A2, type: GP2D12, rate: 10},
  #ir_front_back:       {pin: A3, type: GP2D12, rate: 10},
}
